# Generated by Django 5.2.7 on 2025-11-15 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('html_body', models.TextField(verbose_name='HTML-тело письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон рассылки',
                'verbose_name_plural': 'Шаблоны рассылок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSendJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sending', 'Отправляется'), ('done', 'Завершена'), ('failed', 'Ошибка')], default='queued', max_length=20, verbose_name='Статус')),
                ('total', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('errors', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание отправки')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_jobs', to='newsletters.newslettertemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Задача рассылки',
                'verbose_name_plural': 'Задачи рассылок',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
