# Generated by Django 5.2.7 on 2025-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность (секунды)'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to='adverts/%Y/%m/', verbose_name='Файл'),
        ),
    ]
