# Generated by Django 5.2.7 on 2025-11-15 14:21

import adverts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_rename_media_type_to_type_add_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to=adverts.models.advert_media_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=adverts.models.advert_media_path, verbose_name='Постер (для видео)'),
        ),
    ]
