# Generated by Django 5.2.7 on 2025-11-15 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отклика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('accepted', 'Принят'), ('deleted', 'Удалён')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adverts.advert', verbose_name='Объявление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advert', 'status', '-created_at'], name='replies_rep_advert__852c10_idx'), models.Index(fields=['author', '-created_at'], name='replies_rep_author__9f1aeb_idx')],
            },
        ),
    ]
